name: Prettier

on: 
  pull_request:
        branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
